### ISSUE TITLE
cua?

### ISSUE THREAD

**Issue by luciferasm** [alezost/mwim.el#1]
Thanks for a great package. I'm not currently using cua-mode, but in case I'll start, I just wonder - will mwim work in cua-mode? (I can't test it myself since I'm on a terminal)

**Comment by luciferasm** [comment]
-Oh, sorry, I meant shift-selection (I though that was part of the cua-concept, so that's why I labeled it cua).

**Comment by alezost** [comment]
Thank you for the question!  Now mwim should "honor"
`shift-select-mode`.  (Previously it didn't, but I have just
fixed that).

I have tested "shift selection" like this:

``` el
(global-set-key (kbd "<home>") 'mwim-beginning-of-line-or-code)
(global-set-key (kbd "<end>") 'mwim-end-of-line-or-code)
```

And whenever I press `Shift+Home` or `Shift+End`, a region is
selected.

Feel free to reopen the issue if something is wrong with that.
Thanks again.
