### ISSUE TITLE
mwim-beginning-of-code-or-line doesn't seem to work with hide-ifdef-mode

### ISSUE THREAD

**Issue by yashi** [alezost/mwim.el#10]
Hi,

While in a C buffer with `hide-ifdef-mode` on, and if the cursor is at `...`, which indicates folded code lines, `mwim-beginning-of-code-or-line` doesn't work as I expected.  `move-beginning-of-line`, on the other hand, works fine.

Let me know if you need any other info.

**Comment by alezost** [comment]
Hello, I've just tried on the following example:

```c
#ifdef HAVE_LINUX_SYSINFO
#include <sys/sysinfo.h>
#endif
```

So when I have `hide-ifdef-mode` enabled and the point is placed on
`...`, `mwim-beginning-of-code-or-line` moves the point to the beginning
of line, as expected.  Is it the same for you?  Do you have a recipe to
reproduce your issue?

**Comment by yashi** [comment]
It works with the example, indeed.  I'm sure I saw the symptom a few times but I can't find an [ECM](http://orgmode.org/worg/org-faq.html#ecm) right now.  So, I'm closing this for now and I'll reopen when I find one.

Thank you for your time.

**Comment by yashi** [comment]
Hi,

I think I found an ECM.  But this time in Org mode.  Do you support Org mode?
Here is the file:

```
* test string
* a
  - a


```

0) Make sure to have the last two empty lines.
1) Fold everything.
2) Move to the end of the first line, after the "g".
3) Move to next line with `C-n`.
4) Try moving to the beginning of the line with `C-a`, `mwim-beginning-of-code-or-line`.  You can't.

Bind `org-beginning-of-line` to `C-a` and you can move to the beginning of the line.

**Comment by alezost** [comment]
>    Make sure to have the last two empty lines.
>    Fold everything.
>    Move to the end of the first line, after the "g".
>    Move to next line with C-n.
>    Try moving to the beginning of the line with C-a, mwim-beginning-of-code-or-line. You can't.

Ah, I see.  I think this is not the `mwim` problem.  Try "M-x beginning-of-line": do you experience the same problem? (I do)  Now try "M-x beginning-of-visual-line" and it should work!  So if it works for you, then you can tweak mwim to use it:

```elisp
(setq mwim-beginning-of-line-function 'beginning-of-visual-line)
```

Or better (for symmetry) you may set both mwim variables accordingly:

```elisp
(setq mwim-beginning-of-line-function 'beginning-of-visual-line
      mwim-end-of-line-function 'end-of-visual-line)
```

**Comment by yashi** [comment]
Thank you for the tip.

Unfortunately, `end-of-visual-line` only moves the cursor to the end of window.
I mean, if you are on the long line and `trancate-lines` is `t`, `end-of-visual-line` won't get you to the end of the line.  The same is true if you are at the end of a long line and try to move the beginning.

Do you have any other idea?

**Comment by alezost** [comment]
> Do you have any other idea?

Yes, I have just made some modification (commit 508efa3), that allows to make mode-specific customizations (with `mwim-beginning-of-line-function` and `mwim-end-of-line-function` variables).  And it should support Org-mode by default now.

Let me know if it doesn't work as expected for you.

And thank you for the idea!

**Comment by yashi** [comment]
it works!
Thank YOU for your time and the great tool!
