### ISSUE TITLE
Beginning of comment first when in comment?

### ISSUE THREAD

**Issue by xendk** [alezost/mwim.el#11]
Great package, it was just what I was looking for!

I hadn't thought of jumping to start/end of comments, but it gave me an idea:

Is there any way to configure it so that `C-a`/`C-e` jumps to the start/end of the comment first, when point is inside the comment, but last when outside?

**Comment by alezost** [comment]
> Great package, it was just what I was looking for!

Thank you, I also like it :smile:

> I hadn't thought of jumping to start/end of comments, but it gave me an idea:

> Is there any way to configure it so that C-a/C-e jumps to the start/end of the comment first, when point is inside the comment, but last when outside?

Currently it is not possible, but this is a great idea!  Could you evaluate the following code, and check if `M-x mwim-beginning` and `M-x mwim-end` do what you want?

```elisp
(defun mwim-block-beginning ()
  "Return position in the beginning of code or comment.
If the point is inside a comment, return beginning position of
the current comment, otherwise - of the code."
  (if (mwim-current-comment-beginning)
      (mwim-comment-beginning)
    (mwim-code-beginning)))

(defun mwim-block-end ()
  "Return position in the end of code or line.
If the point is inside a comment, return end position of
the current comment, otherwise - of the code."
  (if (mwim-current-comment-beginning)
      (mwim-line-end)
    (mwim-code-end)))

(with-eval-after-load 'mwim
  (add-to-list 'mwim-beginning-position-functions 'mwim-block-beginning)
  (add-to-list 'mwim-end-position-functions 'mwim-block-end))
```

If you are interested I tested it on the following sample, and it does what you describe (if I understood it correctly)

```elisp
(defvar some-testing-var
  '(mwim-block-end
    mwim-code-end  ; marginal comment
    mwim-line-end)
  ;; Comment on the whole line
  "Some useful foo.")
```

So if it's OK for you, I think this feature should be enabled by default,
thank you for the idea!

**Comment by xendk** [comment]
> Currently it is not possible, but this is a great idea! Could you evaluate the following code, and check if M-x mwim-beginning and M-x mwim-end do what you want?

It does exactly what I want.

> So if it's OK for you, I think this feature should be enabled by default, thank you for the idea!

That would be great. :smiley:

**Comment by alezost** [comment]
Great, committed as e15c5797738ab40b175045939a1d394a1c206340, thank you!
