### ISSUE TITLE
Move to beginning of comment?

### ISSUE THREAD

**Issue by alphapapa** [alezost/mwim.el#6]
It would be handy if `mwim-beginning-of-code-or-line` could also jump to the beginning of a comment, if one exists on that line.

Thanks for this great package!  I think it should be built-in to Emacs.  The shift-selection is really cool, too!

**Comment by alezost** [comment]
Thanks!  Do you mean you want to cycle between 3 positions: beginning of line, code and comment (if it exists)?

**Comment by alphapapa** [comment]
Yes, that's exactly it.  :)

I looked at the code and started to try to implement it myself, but it looked like it would require a lot of restructuring, since the functions and macros are made to alternate between exactly two functions.  So I decided to set that aside for the moment...  ;)

Anyway, if you were able to make a way to use a sequence of functions instead of just two, I can imagine it coming in handy in a lot of modes.  For example, in org-mode, you could have a function that switched between beginning-of-line, beginning-of-heading-text, beginning-of-tags, when on a heading line.  When on a line like a `#+BEGIN_SRC elisp` line, it could switch between beginning-of-line and the `elisp`.  And in something like Python, I can imagine a sequence like, when on a `def` line, switch between beginning-of-line, beginning-of-indentation/code, beginning-of-argument-list...

If you open it up to arbitrary sequences, the possibilities are really interesting.  :)

**Comment by alezost** [comment]
> Yes, that's exactly it. :)

OK, then I think `mwim-beginning-of-code-or-line` is not the right
command to switch between these 3 positions, I would rather add
`mwim-beginning-of-code-or-line-or-comment` command.  WDYT?

> I looked at the code and started to try to implement it myself, but
> it looked like it would require a lot of restructuring, since the
> functions and macros are made to alternate between exactly two
> functions. So I decided to set that aside for the moment... ;)

I didn't think that switching between more than 2 positions could ever
be useful :smile: Indeed, this change will require some messing with
macros but I think I know how to do it.

> Anyway, if you were able to make a way to use a sequence of functions
> instead of just two, I can imagine it coming in handy in a lot of
> modes. For example, in org-mode, you could have a function that
> switched between beginning-of-line, beginning-of-heading-text,
> beginning-of-tags, when on a heading line. When on a line like a #
> +BEGIN_SRC elisp line, it could switch between beginning-of-line and
> the elisp. And in something like Python, I can imagine a sequence
> like, when on a def line, switch between beginning-of-line,
> beginning-of-indentation/code, beginning-of-argument-list...

Hm, interesting, it will probably be good to add some general-purpose
commands (like `mwim-beginning`/`mwim-end`) that will go to points
depending on the current mode (and a user should have a possibility to
customize such points of course), although I don't feel like I wish to
do it soon :-)

> If you open it up to arbitrary sequences, the possibilities are
> really interesting. :)

Yeah, I'm definitely going to generalize
`mwim-goto-non-current-position` macro for an arbitrary number of
expressions.  I'll ping this issue when it will be done.

**Comment by alezost** [comment]
OK, so I have finally finished the mentioned changes.  A short summary:
- Now there is `mwim-beginning-of-code-or-line-or-comment` command that
  switches between 3 positions as you described.
- An arbitrary number of positions to switch between is supported, so
  you can define commands like this:
  
  ``` elisp
  (defun move-somewhere ()
    (interactive "^")
    (mwim-goto-next-position
      (mwim-line-comment-beginning)
      (mwim-line-beginning)
      (+ 7 (line-beginning-position)) ; why not :-)
      (mwim-code-beginning)))
  ```
- Finally, there are `mwim-beginning`/`mwim-end` commands, that can be
  customized to switch between any positions you want.  See README for
  details.

Please, let me know if something is not clear or not working as
expected :-)

**Comment by alphapapa** [comment]
That was quick!  :D  The code looks great, I can't wait to cook up some interesting functions for Org mode and stuff like that.

However, I seem to have found a bug in `mwim-beginning-of-code-or-line-or-comment`:

```
Debugger entered--Lisp error: (error "Unknown upattern `(quote nil)'")
  signal(error ("Unknown upattern `(quote nil)'"))
  error("Unknown upattern `%s'" (quote nil))
  pcase--u1(((match expressions quote nil)) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"  BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((((...) (... ...) (let ... ...)))) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let (...) (if ... ... ...)))))) ((quote nil) fallback-position) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"] nil nil)
  pcase--u((((match expressions quote nil) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"   BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((...)) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ...) (if ... fallback-position ...)))) ((quote nil) fallback-position) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"])))
  pcase--q1(expressions ((\, first) \, rest) nil #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\" BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((((...) (... ...) (let ... ...)))) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let (...) (if ... ... ...)))))) ((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let ((pos (eval first))) (if (and pos (= pos position)) (or (mwim-first-position rest position) fallback-position pos) (mwim-next-position rest position (or fallback-position pos)))))) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"] nil (((match expressions quote nil) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"   BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((...)) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ...) (if ... fallback-position ...)))) ((quote nil) fallback-position) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"])))
  pcase--u1(((match expressions \` ((\, first) \, rest))) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"    BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((((...) (... ...) (let ... ...)))) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let (...) (if ... ... ...)))))) ((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let ((pos (eval first))) (if (and pos (= pos position)) (or (mwim-first-position rest position) fallback-position pos) (mwim-next-position rest position (or fallback-position pos)))))) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"] nil (((match expressions quote nil) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"   BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((...)) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ...) (if ... fallback-position ...)))) ((quote nil) fallback-position) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"])))
  pcase--u((((match expressions \` ((\, first) \, rest)) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\" BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((...)) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ...) (if ... fallback-position ...)))) ((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let (...) (if ... ... ...)))) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"]) ((match expressions quote nil) #[257 "\302\301\242>\204\301\302\301\242B\240\210\303\302A!\203\304\202\300\302A\"\207" [#[514 "\211C\301\242\236\211\204 \302\242\"\301\242E\301\242B\240\210\211\262\202\205\211@A\211@A\211@\2119\204c\303\304\305\300\242G\"!\300\306\307\310\"    BBD\300\242B\240\210\311\240\210\307\312\"B\241\210\211AA\262\240\210\262\313\242!\240\210\307\314\315\316\317\320\f!\321\"\322\323%\"\311BB\262\266\205\262\207" [(nil) ((...)) pcase-codegen make-symbol format "pcase-%d" lambda mapcar car funcall cdr copy-sequence make-byte-code 257 "\211@\300\242\236\300\301\300\242\"\240\210\211A\207" vconcat vector [delq] 6 "\n\n(fn PA)"] 16 "\n\n(fn CODE VARS)"] ((((\` ...) (if ... fallback-position ...)))) ((quote nil) fallback-position) pcase--small-branch-p pcase-codegen] 4 "\n\n(fn VARS)"])))
  pcase--expand(expressions (((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let ((pos (eval first))) (if (and pos (= pos position)) (or (mwim-first-position rest position) fallback-position pos) (mwim-next-position rest position (or fallback-position pos)))))) ((quote nil) fallback-position)))
  #[385 "\301@\"@\232\203 \211A@\262\232\203 \211\211AA\262\202:\211\203(\302\303!\210\304\"\305@BB#\210\211\262\207" [pcase--memoize gethash message "pcase-memoize: equal first branch, yet different" pcase--expand puthash] 9 ("/usr/share/emacs/24.4/lisp/emacs-lisp/pcase.elc" . 892)](expressions ((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let ((pos (eval first))) (if (and pos (= pos position)) (or (mwim-first-position rest position) fallback-position pos) (mwim-next-position rest position (or fallback-position pos)))))) ((quote nil) fallback-position))
  (pcase expressions ((\` ((\, first) \, rest)) (if (and (null rest) fallback-position) fallback-position (let ((pos (eval first))) (if (and pos (= pos position)) (or (mwim-first-position rest position) fallback-position pos) (mwim-next-position rest position (or fallback-position pos)))))) ((quote nil) fallback-position))
  mwim-next-position(((mwim-code-beginning) (mwim-line-beginning) (mwim-comment-beginning)))
  (let ((pos (mwim-next-position expressions))) (if pos (progn (goto-char pos))))
  mwim-move-to-next-position(((mwim-code-beginning) (mwim-line-beginning) (mwim-comment-beginning)))
  (if (or (null arg) (= 0 arg)) (mwim-move-to-next-position (quote ((mwim-code-beginning) (mwim-line-beginning) (mwim-comment-beginning)))) (forward-line arg) (mwim-beginning-of-code))
  mwim-beginning-of-code-or-line-or-comment()
  call-interactively(mwim-beginning-of-code-or-line-or-comment nil nil)
  command-execute(mwim-beginning-of-code-or-line-or-comment)

```

It seems to happen regardless of what major-mode is in use.

**Comment by alphapapa** [comment]
BTW, I was inspired to try my hand at making something similar.  Let me know what you think: https://github.com/alphapapa/mosey.el

**Comment by alezost** [comment]
> However, I seem to have found a bug in
> mwim-beginning-of-code-or-line-or-comment:
> 
> Debugger entered--Lisp error: (error "Unknown upattern `(quote nil)'")
>   signal(error ("Unknown upattern`(quote nil)'"))

Ah, thanks a lot!  I think you use Emacs 24, and I've just found that in
Emacs 24, `pcase` doesn't support `'()` pattern.  I use Emacs 25, so I
never noticed this, fixed by commit a8c6f679d39c62cf16889aed23978ba8b08bf93b.

**Comment by alezost** [comment]
> BTW, I was inspired to try my hand at making something similar. Let
> me know what you think: https://github.com/alphapapa/mosey.el

Aha!  So it's a competitive package :rage:  No anger, I'm joking :-)

It's great, I mean I often don't like how other people do packages, so
sometimes I do my own similar packages.  And if I were you and I thought
that this jumping between positions should be implemented differently, I
would do another package, so I think it's great that you made an
alternative package!

**Comment by alphapapa** [comment]
> Ah, thanks a lot! I think you use Emacs 24,

Yeah, still on 24.4 and 24.5 here.  I'll upgrade eventually, kinda busy right now though, and I'd have to build the package myself for my Ubuntu Trusty systems...

> Aha! So it's a competitive package :rage: No anger, I'm joking :-)

LOL  :D  I don't know if it actually competes with `mwim`, because your package seems much more powerful.  I just had a sudden inspiration and ran with it.  I was having a hard time wrapping my ahead around how to configure `mwim` with custom functions, so I came up with something easier for me to grok.  I don't know if it will amount to anything, but it was fun and I learned more about Emacs in the process.  I will continue to study and learn from your work!  :)

**Comment by alezost** [comment]
> I was having a hard time wrapping my ahead around how to configure mwim with custom functions, so I came up with something easier for me to grok.

Yeah, I would do the same :-)  Just to mention, if you want a universal function that will do the same as `mosey/forward-cycle`, it can be written like this:

``` elisp
(defun move-anywhere ()
  (interactive)
  (mwim-goto-next-position
    (mwim-line-beginning)
    (mwim-code-beginning)
    (mwim-code-end)
    (mwim-point-at (mosey/goto-beginning-of-comment-text))
    (mwim-line-end)))
```

BTW, it's a good idea to move to the comment text, and not to the beginning of comment.  I think I should change `mwim-comment-beginning` to return this comment text position instead of the comment beginning position.  Thanks for this idea!

I think the main difference between our packages is that in `mosey` you calculate all positions at once, while in `mwim` positions are calculated only when needed: when the first position that is the same as the current point is found, we move to the next one, all the rest positions are not calculated.  In theory it should be faster (a user will unlikely ever notice the speed difference though), but it has downsides, so the `mosey` way looks cleaner.  Well, at least, there is something to think about for me; thanks!

**Comment by alphapapa** [comment]
> Just to mention, if you want a universal function that will do the same as mosey/forward-cycle, it can be written like this:

Yeah, I saw that eventually.  :D  Maybe you should move it higher in the readme, cause it seems like one of the most useful, easy-to-understand parts is buried at the bottom  :)

> BTW, it's a good idea to move to the comment text, and not to the beginning of comment. I think I should change mwim-comment-beginning to return this comment text position instead of the comment beginning position. Thanks for this idea!

:)

> I think the main difference between our packages is that in mosey you calculate all positions at once, while in mwim positions are calculated only when needed: when the first position that is the same as the current point is found, we move to the next one, all the rest positions are not calculated. In theory it should be faster (a user will unlikely ever notice the speed difference though), but it has downsides, so the mosey way looks cleaner.

Yeah, I don't think the speed will be an issue in normal use, but you're right that it's less optimal.  "Early optimization" and all that...  ;)  Maybe I'll experiment with different versions that do it in different ways...  Also the `:backward` and `:cycle` options let the user control the direction and looping, something like that would be handy in `mwim-goto-next-position`.

Actually, if I could make one more suggestion, it would be to rename `mwim-goto-next-position`.  If I understand correctly, it doesn't care about direction, so it's not necessarily the `next` (as opposed to the previous) position it goes to.  Something like `mwim-move-anywhere` might describe its all-inclusive purpose better.  :)

Well, through collaboration and/or competition, I'm learning, and both our packages are improving!  :)

**Comment by alezost** [comment]
> Also the :backward and :cycle options let the user control the direction and looping, something like that would be handy in mwim-goto-next-position.

I have added support for sorting positions, so moving backwards is also
possible now.  As for disabling cycling, I don't see how it can be
useful; I think if the point is moved to the last position it is natural
to move it to the first one next time.

> Actually, if I could make one more suggestion, it would be to rename
> mwim-goto-next-position. If I understand correctly, it doesn't care
> about direction, so it's not necessarily the next (as opposed to the
> previous) position it goes to. Something like mwim-move-anywhere
> might describe its all-inclusive purpose better. :)

It cares about direction in the sense it moves to the next position
specified in `mwim-goto-next-position`.  If you specify positions in
another order then you will move to the next position in this order.  I
mean unlike `mosey`, in `mwim` positions are not sorted by default: so
if you want to switch between line, code and comment start in `mosey`,
it can only be this or the reverse order, while in `mwim` it can be any
order (for example: `comment, line, code`, etc.)

> Well, through collaboration and/or competition, I'm learning, and
> both our packages are improving! :)

Definitely!  I took several ideas from `mosey` (for example, I switched
from evaluating expressions to using functions).  I think both our
packages will have their niches, and a user (who reads README) can find
the other package (I have also added a mention about `mosey.el` to
`mwim`'s README).

Oh, one last thing: in `mosey-goto-beginning-of-comment-text` you search
for comment-start syntax.  This is not always reliable.  For example, open
a buffer in `c-mode`, and insert a line with comment there:

``` c
int foo;  // comment
```

`M-x mosey-forward-cycle` will never move you to the beginning of the
comment.  You can use `comment-search-forward` function to do this.

**Comment by alphapapa** [comment]
> As for disabling cycling, I don't see how it can be useful; I think if the point is moved to the last position it is natural to move it to the first one next time.

I guess it depends on what the user binds it to.  If they use it as a replacement for `C-a`/`C-e`, they might want to hold down `C-a` and get to the beginning of the line.  But if it cycled, they would have to be careful to press it just the right number of times, or else it would cycle around and go past the point they wanted.

> It cares about direction in the sense it moves to the next position specified in mwim-goto-next-position. If you specify positions in another order then you will move to the next position in this order. I mean unlike mosey, in mwim positions are not sorted by default: so if you want to switch between line, code and comment start in mosey, it can only be this or the reverse order, while in mwim it can be any order (for example: comment, line, code, etc.)

Yeah, if you have an idea in advance of what order the things on the current line will be in, then that should work pretty well.  I've been thinking about adding functions to do things like jump to the next/previous quoted string, parenthesis/brace, comma/colon (depending on the language), and those would appear in an unpredictable order, so that would require sorting to work right.  I can imagine both types being useful.

> I think both our packages will have their niches, and a user (who reads README) can find the other package (I have also added a mention about mosey.el to mwim's README).

Yeah, mwim is definitely more powerful and featureful.  I'm not sure if mosey will be very useful in comparison, but I'm having fun and learning.  It's nice of you to add it to the readme.  :)

> You can use comment-search-forward function to do this.

Thanks!  I didn't think about languages with multiple comment-starting strings.  I'll have to fix that.  :)
