### ISSUE TITLE
mwim-end-of-code wrong position

### ISSUE THREAD

**Issue by jdufresne** [alezost/mwim.el#7]
The line contains:

```
                $foo->bar->baz->fizz->onchange = "selectAll(this, $zork_buzz, $numbers);";
```

The code is PHP, noticed in `php-mode`, but the bug also occurs in `text-mode`.

The command `mwim-end-of-code` moves to the point to the "r" in "`$numbers`". I expect that it would move to after the last semi-colon.

**Comment by alezost** [comment]
Hm, not sure I understand, but this line is rather long.  Does it fully fit your screen?  If not, then you probably were moved to the end of visual line (`end-of-visual-line` is the default value of `mwim-end-of-line-function`).  Do you get what you need after `(setq mwim-end-of-line-function 'end-of-line)`?

**Comment by alezost** [comment]
After thinking more, I have changed default values of these variables (commit 1be8bc79f60c69f226e3d7652894fa6c4bd4a116).

@jdufresne, do you still have this issue?  If yes, could you please give a recipe to reproduce it?

**Comment by jdufresne** [comment]
Thanks for the response, sorry for the delay.

No longer see the issue. Thanks.
