### ISSUE TITLE
add defun mwim() from README into library

### ISSUE THREAD

**Issue by articuluxe** [alezost/mwim.el#8]
I wish to use the example at the end of the README, `mwim()`, and bind "M-m" to it.  Using use-package, the library itself is not autoloaded, and the binding fails at runtime.  I think because the key is bound to a local defun in my config, and not the library.  I need to add `:demand t` to my use-package declaration for `mwim`.  I would prefer to autoload this library rather than doing this.

Anyway, this looks like a useful function IMO and I would suggest putting it in the library anyway.

**Comment by alezost** [comment]
> I wish to use the example at the end of the README, mwim(), and bind "M-m" to it.

Wow, I've just noticed this issue, and...  I have already added `mwim`
command as I had the same thought as you :smile: Note that along with
code/line start/end positions it will also move you to a comment start
(if it exists on the current line).  But it is only by default,
positions to switch between can be customized (see
https://github.com/alezost/mwim.el#move-where-you-really-want for
details).

> Using use-package, the library itself is not autoloaded, and the binding fails at runtime. I think because the key is bound to a local defun in my config, and not the library. I need to add :demand t to my use-package declaration for mwim. I would prefer to autoload this library rather than doing this.

I don't understand, what you mean «the library itself is not
autoloaded»?  Only functions/variables can be autoloaded, but not
libraries.

> Anyway, this looks like a useful function IMO and I would suggest putting it in the library anyway.

Yeah, I also realized it, so I believe you can use it now.

Let me know if you think something is not clear or is not working
properly, thanks.

**Comment by articuluxe** [comment]
It looks good now, and works beautifully. 
Thanks for a good package!
