### ISSUE TITLE
Support for `visual-line-mode`?

### ISSUE THREAD

**Issue by timmli** [alezost/mwim.el#9]
I'm using `visual-line-mode` when editing LaTeX files and <kbd>C-a</kbd> is therefore bound to `beginning-of-visual-line`, which makes sense. Would it be possible to jump to the beginning of the physical line only when being at the beginning of a visual line? That would be great!

(and conversely for `end-of-visual-line`)

**Comment by alezost** [comment]
Hi!  Does the following do what you need?

```elisp
(setq mwim-beginning-of-line-function 'beginning-of-visual-line
      mwim-end-of-line-function 'end-of-visual-line)
```

**Comment by timmli** [comment]
Thanks! Unfortunately, this is does only a part of what I'd like to achieve: When calling `mwim-beginning-of-code-or-line` from somewhere within a visual line, the cursor is now correctly moved to the beginning of the visual line. But a second use of `mwim-beginning-of-code-or-line` won't move the cursor to the beginning of the physical line (like `beginning-of-line`).

**Comment by alezost** [comment]
Right: you either move to the beg/end of the whole line or inside a visual line.  Switching between beg/end of a visual line and a physical line is impossible, sorry :-(

**Comment by ile-du-fantome** [comment]
Almost eight years later, and [with no small amount of help](https://tildes.net/~tech/1i5f/gitlab_is_reportedly_up_for_sale#comment-deqc), I put this together:

```emacs
(use-package mwim
  :custom
  (mwim-beginning-of-line-function 'beginning-of-visual-line)
  (mwim-end-of-line-function 'end-of-visual-line)

  :config
  (defun smart-beginning-of-line ()
    (interactive
     (progn
       (handle-shift-selection)))
    (let ((start (point)))
      (mwim-beginning-of-code-or-line-or-comment)
      (when (equal (point) start)
        (beginning-of-line))))

  (defun smart-end-of-line ()
    (interactive
     (progn
       (handle-shift-selection)))
    (let ((end (point)))
      (mwim-end)
      (when (equal (point) end)
        (end-of-line))))

  :bind (("<home>" . smart-beginning-of-line)
         ("<end>" . smart-end-of-line)))
```

It's 95% of the way there, but stops working correctly when you use `end` on a line that is visually wrapped *and* ends with a comment.

Honestly, with the amount of time I have spent on getting this to work, I can live with that 5% of weirdness. If someone else sees this and knows a better solution, please let me know.

Finally, you can test the buggy behavior on this line:

```emacs
    (global-set-key (kbd "<end>") 'smart-end-of-line) ;; This is a line of code that ends in a comment that is so long that it wraps. This breaks the smart-end-of-line function. When the point is on any of the visual lines of this comment, hitting <end> will move the point to the end of that visual line. Hitting <end> a second time will move the point to the end of the code before this comment. Hitting <end> a third time will move the point to the end of the first visual line. Subsequent presses of <end> will cycle the point between the end of the code and the end of the visual line.
```
